name: Bug Report
description: Report an unexpected behavior or issue
labels: ['bug']
body:
  - type: checkboxes
    attributes:
      label: Has this bug been reproduced?
      options:
        - label: I was able to reproduce the bug
        - label: The bug is intermittent

  - type: textarea
    attributes:
      label: Bug Description
      description: Describe the problem clearly and concisely

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: |
        1. Go to the page...
        2. Click on...
        3. The bug occurs when...
      placeholder: '1. Go to the flags page...'

  - type: textarea
    attributes:
      label: Expected Behavior
      description: What should happen?

  - type: textarea
    attributes:
      label: Actual Behavior
      description: What actually happens?

  - type: textarea
    attributes:
      label: Screenshots / Videos
      description: Add screenshots if relevant

  - type: dropdown
    attributes:
      label: Game Mode Affected
      options:
        - Flags
        - Languages
        - Both
        - Other

  - type: input
    attributes:
      label: Browser / OS
      description: 'Chrome 120 on macOS 14'

  - type: checkboxes
    attributes:
      label: Additional Information
      options:
        - label: The bug prevents continuing the quiz
        - label: The bug affects mobile display
        - label: The bug is related to the timer
